---
- hosts: undercloud
  tasks:
    - name: delete overcloud
      shell: |
        source ~/stackrc
        openstack overcloud node unprovision --all ~/virt/network/baremetal_deployment.yaml -y
      ignore_errors: yes
    
    - name: move the nodes to manageable state
      shell: |
        source ~/stackrc
        for i in $(openstack baremetal node list -c UUID -f value); do openstack baremetal node manage $i; done
   
    - name: clean the nodes and move to available
      shell: |
        source ~/stackrc
        openstack overcloud node clean --all-manageable --provide
      ignore_errors: yes
     
    - name: move the nodes to available state
      shell: |
        source ~/stackrc
        for i in $(openstack baremetal node list -c UUID -f value); do openstack baremetal node provide $i; done
